import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppBackground from "./components/AppBackground";
import GridBackground from "./components/GridBackgroud";
import Footer from "./components/Footer";
import UAppBar from "./components/UAppBar";
import BannerFollowInstagram from "./components/banners/follow-instagram";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}
      >

        <div className="fixed inset-0">
          <AppBackground />
        </div>
        <div className="fixed inset-0">
          <GridBackground />
        </div>
        <div className="absolute inset-0 content-wrapper">
          <div className="hidden md:block">
            <UAppBar />
          </div>
          {children}

          <div className="fixed bottom-0 left-0 right-0 z-50">
            <BannerFollowInstagram />
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
